---
- get_url: url="{{epel_repo_url}}" dest=/tmp/{{epel_repo_rpm}}

- name: Install EPEL repo.
  command: rpm -iv /tmp/{{epel_repo_rpm}}
  ignore_errors: yes

- file: path=/tmp/{{epel_repo_rpm}} state=absent

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
